### ISSUE TITLE
元素中不能创建元素

### ISSUE THREAD

**Issue by ciel-he** [pearmini/gossip#13]

**Comment by pearmini** [comment]
在容器元素中可以创建元素，其他类型的元素中不能创建元素，您看是这个原因吗？

**Comment by heye1109** [comment]
> 在容器元素中可以创建元素，其他类型的元素中不能创建元素，您看是这个原因吗？

在容器元素上创建，点击没有反应

**Comment by pearmini** [comment]
谢谢反馈，现在已经修复
