### ISSUE TITLE
有点期待 “一个高效创建和演示炫酷邮件的用户界面”

### ISSUE THREAD

**Issue by vioulo** [pearmini/gossip#6]
最近做的事有点被邮件模板困扰，看到你这个炫酷的 PPT 用户界面，算是看到了希望 :dog:

**Comment by pearmini** [comment]
感谢肯定！不过炫酷邮件和邮件模版是指啥？

**Comment by vioulo** [comment]
> 感谢肯定！不过炫酷邮件和邮件模版是指啥？

拖拽条目然后组成一个邮件模板这样 :dog:
